#ifndef _PIN_DEFINES_H
#define _PIN_DEFINES_H

#define SPI_MISO_PIN 0
#define SPI_MOSI_PIN 3
#define SPI_SCLK_PIN 2

#define GPIO_EXPANDER_0_RST_PIN 6
#define GPIO_EXPANDER_0_INT_PIN 7
#define GPIO_EXPANDER_0_CS_PIN 1

#define LED_R TINY2040_LED_R_PIN
#define LED_G TINY2040_LED_G_PIN
#define LED_B TINY2040_LED_B_PIN

#endif // _PIN_DEFINES_H