#ifndef _TASK_DEFINES_H
#define _TASK_DEFINES_H

#include "FreeRTOSConfig.h"

#define USB_DEVICE_TASK_PRIORITY ( tskIDLE_PRIORITY + 1UL )
#define SPI_TASK_PRIORITY ( tskIDLE_PRIORITY + 2UL )
#define HID_TASK_PRIORITY ( tskIDLE_PRIORITY + 2UL ) // Priority?

#define USB_DEVICE_TASK_STACK_SIZE configMINIMAL_STACK_SIZE
#define SPI_TASK_STACK_SIZE configMINIMAL_STACK_SIZE
#define HID_TASK_STACK_SIZE configMINIMAL_STACK_SIZE


#endif // _TASK_DEFINES_H